FROM python:2.7-onbuild

MAINTAINER isiddhesh45@gmail.com

RUN pip install --upgrade pip
ADD HelloWorld.py /HelloWorld.py
ADD requirements.txt /requirements.txt
RUN pip install -r /requirements.txt

CMD [ "python", "./HelloWorld.py" ]
